package pl.edu.agh.kis.ooprogramming.example;

import lombok.extern.slf4j.Slf4j;


@Slf4j
public class App {
    public static void main(String[] args) {
        App application = new App();
        log.info("Value retruned from library is: {}", application.library.someLibraryMethod());
    }

    //from now on this field is automatically generated by lombok's annotation @Slf4j
    /*private static final Logger log =  LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());*/

    private Library library = new Library();
} 
